return {
    -- "folke/tokyonight.nvim",
    -- lazy = false,
    -- priority = 1000,
    -- config = function()
    --     require("tokyonight").setup({
    --         style = "night",
    --         on_colors = function(colors)
    --             colors.bg = "#282c34"
    --             colors.bg_float = "#282c34"
    --             colors.bg_popup = "#282c34"
    --             colors.bg_sidebar = "#282c34"
    --             colors.bg_statusline = "#282c34"
    --         end,
    --         styles = {
    --             comments = { italic = false },
    --             keywords = { italic = false },
    --         },
    --     })
    -- end,
}
